backend/controllers/SiteController.php
<?php

namespace backend\controllers;

use backend\components\Controller;
use backend\models\OrderSearch;
use Yii;
use common\models\LoginForm;
use common\models\Status;
use yii\helpers\Json;

class SiteController extends Controller {

    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function actionIndex() {
        $user = Yii::$app->user->getIdentity();

        $ordersSearch   = new OrderSearch();
        $ordersProvider = $ordersSearch->searchUserOrders(Yii::$app->request->queryParams);

        $statuses_list  = Status::find()->select('name')->indexBy('id')->column();

        return $this->render('profile', [
            'user'           => $user,
            'ordersSearch'   => $ordersSearch,
            'ordersProvider' => $ordersProvider,
            'statuses_list'  => $statuses_list,
        ]);
    }

    public function actionLogout() {
        Yii::$app->user->logout();

        return $this->redirect('/');
    }

    /**
     * Ajax server.
     */
    public function actionSavePanelSettings() {
        Yii::$app->user->identity->panel_settings = Json::encode(Yii::$app->request->post('settings'));
        Yii::$app->user->identity->save();
    }

    public function actionResetPanelSettings() {
        Yii::$app->user->identity->panel_settings = null;
        Yii::$app->user->identity->save();

        return $this->redirect(Yii::$app->request->referrer);
    }

}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\components\Controller;
use common\models\Locality;
use common\models\Service;
use common\models\ServiceType;
use common\models\Settings;
use common\models\User;
use common\models\Company;
use common\models\QuickSearch;
use Yii;
use yii\helpers\Json;
use yii\web\NotFoundHttpException;
use yii\web\Response;
use yii\web\ServerErrorHttpException;

class SiteController extends Controller {
    public function actions() {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex() {
        // Ссылки быстрого поиска
        $quickSearch = QuickSearch::find()->
                with(['serviceType'])->
                where(['is_show' => 1])->
                limit(8)->
                all();

        return $this->render('index', [
            'about' => Settings::getSetting('about'),
            'banner' => Settings::getSetting('banner'),
            'quickSearch' => $quickSearch,
        ]);
    }

    public function actionDetails($url) {
        $service = Service::find()->
                from(['s' => Service::tableName()])->
                leftJoin(['c' => Company::tableName()], 'c.id = s.company_id')->
                leftJoin(['u' => User::tableName()], 'u.id = c.user_id')->
                where(['AND', 's.url=:url', 's.is_blocked!=1', 'c.is_blocked!=1', 'u.is_blocked!=1'], [':url' => (string) $url])->
                one();

        if (!$service) {
            throw new NotFoundHttpException('service not found');
        }

        return $this->render('detail', [
            'model' => $service,
            'discount_condition_text' => Settings::getSetting('discount_condition_text'),
        ]);
    }

    public function actionSearch($service_type = null, $chars = null, $localities = null, $page = 0) {
        $request = Yii::$app->getRequest();

        $priceFrom = $request->get('price_from');
        $priceTo = $request->get('price_to');
        $search = trim($request->get('search'));
        $sort = trim($request->get('sort'));

        $sort = ($sort == 'price_desc' ? 's.price DESC' : 's.price ASC');
        $page = $page < 0 ? 0 : $page;

        $selectedChars = [];

        if (empty($service_type)) {
            // Выведим фильтр "Коллекция", если не выбран раздел
            // Найдем первый товар с указанным названием и выставим категорию для поиска
            if (!empty($search)) {
                $service_type = Service::findNotBlocked()->
                        select(['s.service_type_id'])->
                        andWhere(['s.name' => $search])->
                        limit(1)->
                        scalar();
            }
        }

        // Быстрый поиск
        $url = $request->get('url');
        if (!empty($url)) {
            $quickSearch = QuickSearch::findOne(['url' => (string) $url]);
            if (!$quickSearch instanceof QuickSearch) {
                throw new NotFoundHttpException('page not found');
            }

            if (is_null($chars)) {
                $chars = Json::encode($quickSearch->doSearch());
            }

            if (is_null($service_type)) {
                $service_type = $quickSearch->service_type_id;
            }
        } else {
            $quickSearch = null;
        }

        $serviceType = ServiceType::findOne(['id' => (int) $service_type]);
        if (!$serviceType instanceof ServiceType) {
            //return $this->redirect(['/']);
        }

        $chars = Json::decode($chars);
        $localities = Json::decode($localities);

        $query = Service::doSearch($chars, $service_type, Json::encode($localities), $priceFrom, $priceTo);



        // Поиск по фразе
        if (!empty($search)) {
            $query->andWhere(['OR', ['LIKE', 's.name', $search], ['LIKE', 's.code', $search]]);
        }

        $limit = 45;

        $pages = ceil($query->count() / $limit);
        $searchResult = $query->
                orderBy($sort)->
                offset($page * $limit)->
                limit($limit)->
                all();

        $serviceCharValues = [];
        foreach ($searchResult as $service) {
            if ($service->chars === null) {
                continue;
            }

            foreach ($service->chars as $char) {
                if (isset($serviceCharValues[$char->char_id])) {
                    if (!in_array($char->value_id, $serviceCharValues[$char->char_id])) {
                        $serviceCharValues[$char->char_id][] = $char->value_id;
                    }
                } else {
                    $serviceCharValues[$char->char_id][] = $char->value_id;
                }
            }
        }

        if (\Yii::$app->request->isAjax) {
            Yii::$app->response->format = Response::FORMAT_JSON;

            return [
                'serviceCharValues' => $serviceCharValues,
                'html' => $this->renderPartial('group-items', [
                    'services' => $searchResult,
                ]),
                'nextPage' => $pages > $page + 1 ? $page + 1 : -1,
            ];
        }

        return $this->render('search', [
            'pages' => $pages,
            'serviceType' => $serviceType,
            'searchResult' => $searchResult,
            'chars' => $chars,
            'serviceCharValues' => $serviceCharValues,
            'quickSearch' => $quickSearch,
            'search' => $search,
            'selectedChars' => $chars,
        ]);
    }

    /**
     * Запрос на восставноление пароля
     * @return type
     */
    public function actionResetAccess() {
        $email = (string) Yii::$app->getRequest()->post('email');

        $user = User::findOne([
                    'email' => $email,
                    'is_blocked' => 0,
        ]);
        if ($user instanceof User) {
            $user->requestResetPassword();

            return Json::encode(['status' => 'success', 'message' => 'На ваш e-mail отправлено письмо с инструкциями для восстановления пароля.']);
        } else {
            return Json::encode(['status' => 'error', 'message' => 'E-mail не найден.']);
        }
    }

    /**
     * Сброс пароля
     * @return type
     */
    public function actionResetPassword($token) {
        $user = User::findByPasswordResetToken($token);

        if ($user instanceof User) {
            Yii::$app->session->setFlash('notify', 'На ваш e-mail отправлен новый пароль.');

            $user->resetPassword();
        }

        return $this->redirect('/');
    }

    public function actionLoadMore($page = 2) {
        $services = Service::find()->where(['is_popular' => 1])->limit(3)->offset(($page - 1) * 3);

        return $this->renderPartial('popular', [
                    'services' => $services,
        ]);
    }

    public function actionParseRegions() {
        throw new ServerErrorHttpException('test error');
        if (($handle = fopen("regions.csv", "r")) !== FALSE) {
            while (($data = fgetcsv($handle, 1000, ",")) !== FALSE) {
                $locality = new Locality(['region_id' => 3, 'name' => $data[2]]);
                $locality->save();
            }
            fclose($handle);
            die('ok');
        } else {
            die('error');
        }
    }

}

frontend/views/site/activate-account.php
<?php
/**
 * @var $this  \yii\web\View
 * @var $model \common\models\User
 */

use \yii\bootstrap\ActiveForm;
use \yii\bootstrap\Html;
?>

<div id="finish-registration" class="restore-modal">
    <div class="cross" id="restore-cross"></div>
    <div class="modal-window">
        <h2>Завершите регистрацию</h2>

        <?php $form = ActiveForm::begin([
            'action' => 'auth/finish-registration',
            'enableAjaxValidation' => true,
        ]) ?>
            <?= $form->field($model, 'id')->label(false)->hiddenInput() ?>
            <?= $form->field($model, 'email')->label($model->getAttributeLabel('email')); ?>
            <?= Html::input('submit', 'Отправить') ?>
        <?php ActiveForm::end() ?>
    </div>
</div>

frontend/views/site/confirm-registration.php
<?php
/**
 * @var $this \yii\web\View
 */

use \yii\bootstrap\ActiveForm;
use \yii\bootstrap\Html;
use \yii\helpers\Url;
?>

<div id="confirm-registration" class="restore-modal">
    <div class="cross" id="restore-cross"></div>
    <div class="modal-window">
        <h2>Завершите регистрацию</h2>

        <p>На Ваш E-Mail было отправлено письмо с подтверждением регистрации</p>
        <a href="<?= Url::to(['auth/reset-registration']) ?>">Повторить отправку</a>
    </div>
</div>

frontend/views/site/detail.php
<?php

/**
 * @var $this  \yii\web\View
 * @var $model \common\models\Service
 */
use yii\helpers\Url;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use frontend\widgets\catalog\CatalogWidget;
use frontend\widgets\service\PopularWidget;
use frontend\widgets\service\ServiceBuyWidget;
use frontend\widgets\header\HeaderWidget;
use branchonline\lightbox\Lightbox;
use yii\bootstrap\Modal;
$this->title = !empty($model->meta_title) ? $model->meta_title : $model->name;
$this->registerMetaTag([
    'name' => 'description',
    'content' => $model->meta_description,
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => $model->meta_keywords,
]);

$price = $model->getPriceLabel(true);
$images = $model->images;
?>
<div class="main-section">
    <div class="container">
        <div class="wrap flex-wrapper">

            <?= CatalogWidget::widget() ?>

            <div class="right-part flex-wrapper flex-space-b padding-lr-15 flex-dir-col">
                <?= HeaderWidget::widget() ?>
            </div>
        </div>

        <ol class="breadcrumb padding-lr-15">
            <li><a href="/">Главная</a></li>
            <li><a href="<?= Url::to(['/site/search']) ?>">Каталог</a></li>
            <?php if (!is_null($model->serviceType)): ?>
                <li><a href="<?= Url::to(['/site/search', 'service_type' => $model->serviceType->id]) ?>"><?= Html::encode($model->serviceType->name) ?></a></li>
            <?php endif; ?>
            <li class="active"><a href="#"><?= Html::encode($model->name) ?></a></li>
        </ol>

        <div class="product-wrap padding-lr-15">
            <div class="product">
                <div class="parts flex-wrapper">
                    <div class="left-part">
                        <div class="img-group  <?php if (count($images) == 1) echo "one-img-group" ?> flex-wrapper flex-dir-col flex-space-b">
                            <!--change load svg or gif-->
                          <style>#prod-img { background-image: url(../img/load.svg)}</style>
                            <div class="img-wrap flex-wrapper flex-align-center" id="prod-img">
                                <?= Lightbox::widget([
                                    'files' => [
                                        [
                                            'thumb' => $images ? $images[0]->getUrlPrev() : '/img/img-prod1.jpg',
                                            'original' => $images ? $images[0]->getUrlImage() : '/img/img-prod1.jpg',
                                        ],
                                    ]
                                ])
                                ?>

                                <?php if (count($images) > 1): ?>

                                  <div class="img-slide-panel">
                                    <?php $slide_counter = 0 ?>

                                    <?php foreach($images as $img): ?>
                                      <span class="img-slide-point <?php if($slide_counter == 0) echo 'active'?>" data-src="<?= $img->getUrlPrev() ?>" data-href="<?= $img->getUrlImage()?>" data-id="<?php echo $slide_counter ?>"></span>

                                      <?php $slide_counter++ ?>
                                    <?php endforeach ?>
                                  </div>
                                <?php endif ?>

                            </div>

                        </div>
                    </div>
                    <div class="right-part flex-wrapper flex-dir-col">
                        <div>
                            <div class="h2-group">
                                <h2><?= Html::encode($model->name) ?></h2>
                                <div class="articul-group flex-wrapper flex-space-b flex-align-center">
                                    <?php if (!empty($model->in_stock)): ?>
                                        <p class="presence">Товар в наличии</p>
                                    <?php else: ?>
                                        <p class="presence no-stock">Товара нет в наличии</p>
                                    <?php endif; ?>
                                    <?php if (!empty($model->code)): ?>
                                        <p class="articul">Артикул: <?= $model->code ?></p>
                                    <?php endif; ?>
                                </div>
                            </div>
                            <div class="compare-wrap">
                                <?php echo Html::a(
                                    '',
                                    //'<span class="glyphicon glyphicon-stats"></span> Добавить к сравнению',
                                    '#',
                                    ['item-id'=>$model->id, 'class'=>'compare-link']
                                );?>
                            </div>
                            <div class="price-and-discount-wrap">
                                <div class="price-wrap">
                                <?php if (Yii::$app->user->id && Yii::$app->user->identity->discountToUser): ?>
                                    <p class="old-price"><?= $price?></p>
                                    <p class="item-price">
                                        <?= number_format(
                                            $model->price * (1-Yii::$app->user->identity->discountToUser->discount->discount),
                                            2, '.', ' '
                                        ) ?> &#8381; <span>Ваша цена</span>
                                    </p>
                                <?php else: ?>
                                    <p class="item-price"><?= $price?></p>
                                <?php endif ?>
                                </div>

                                <div class="want-discount-wrap">
                                <?php //if (Yii::$app->user->isGuest || !Yii::$app->user->identity->discountToUser): ?>
                                <?php Modal::begin([
                                    'header' => '<h4 class="modal-title">Условия предоставления цены</h4>',
                                    'toggleButton' => ['tag'=>'a', 'label' => 'Хочу получить скидку на товар', 'class'=>'cond'],
                                ]);?>

                                <?php echo $discount_condition_text;?>

                                <?php Modal::end();?>
                                <?php //endif; ?>
                                </div>
                            </div>
                            <div class="add-to-wrap">
                                <div class="buy-button-wrap">
                                    <?php echo Html::button('<span class="glyphicon glyphicon-shopping-cart"></span>&nbsp;Добавить в корзину', ['item-id'=>$model->id,'class'=>'blue-button buy-button']) ?>
                                </div>
                                <div class="add-to-favorites">
                                    <?php echo Html::a('<span class="glyphicon glyphicon-heart-empty"></span>&nbsp;Сохранить в избранное',
                                        '#',
                                        ['item-id'=>$model->id,'class'=>'favorite-link']
                                    ) ?>
                                </div>
                            </div>
                        </div>
                        <div class="text-group" style="display: none;">
                            <p class="top">Курьерская доставка СДЭК - <span>410 руб</span>. Дата доставки после 1 июля</p>
                            <h3>Другие способы доставки</h3>
                            <p>Пункт выдачи boxberry - <span>410 руб</span>. Дата доставки после 1 июля</p>
                            <p>Пункт выдачи boxberry - <span>410 руб</span>. Дата доставки после 1 июля</p>
                            <a href="#" class="show-ways">Показать все способы доставки</a>
                        </div>
                    </div>
                </div>
                <?php if (!empty($model->description)): ?>
                    <div class="paragraph not-reset">
                        <h2>Описание товара</h2>
                        <p><?= $model->description ?></p>
                    </div>
                <?php endif; ?>
                <div class="paragraph">
                    <h2>Характеристики</h2>
                    <div class="columns">
                        <?php foreach ($model->getCharsValues() as $key => $char): ?>
                            <?php if ($char->is_show): ?>
                                <div class="string flex-wrapper flex-space-b">
                                    <p class="charact-title flex-shrink-0"><?= Html::encode($char->name) ?></p>
                                    <div class="points flex-grow-1"></div>
                                    <p class="charact"><?= Html::encode(implode(', ', ArrayHelper::getColumn($model->getCharValues($char->id), 'name'))) ?></p>
                                </div>
                            <?php endif ?>
                        <?php endforeach ?>
                    </div>
                </div>
            </div>
        </div>

    </div>
</div>
<style type="text/css">
    .product .compare-wrap,
    .product .price-and-discount-wrap,
    .product .add-to-wrap {
        padding: 0 0 20px;
        margin: 20px 0;
        border-bottom: 1px solid #e5e5e5;
        display: flex;
        justify-content: space-between;
    }
    .product .compare-wrap {
        padding: 0; /*TEMPORARY!!!!*/
    }
    .product .add-to-wrap {
        border: none;
        align-items: baseline;
    }
    .product .price-and-discount-wrap{
        align-items: flex-end;
    }

    .product .price-wrap .old-price {
        color: #909090;
        font-size: 21px;
        text-decoration: line-through;
        text-indent: 5px;
        margin-bottom: 10px;
        font-family: 'PT Sans', serif;
        font-weight: bold;
    }
    .product .price-wrap .item-price {
        text-indent: 5px;
        font-size: 28px;
        color: #528cbc;
    }
    .product .price-wrap .item-price span{
        font-size: 15px;
        vertical-align: top;
        font-weight: 100;
    }

    .product .add-to-wrap .buy-button {
        padding: 0px 20px;
        font-size: 18px;
        box-shadow: none;
    }


    .product-wrap .product .parts .right-part a.cond {
        margin: 0;
        cursor: pointer;
    }

    .product .compare-link,
    .product .favorite-link{
        font-family: 'Roboto-Condensed', sans-serif;
        font-size: 17px;
    }
    .product .favorite-link {
        vertical-align: middle;
    }
    .product .compare-link span{padding-right: 7px;}

    @media(max-width: 550px) {
        .product .add-to-wrap .buy-button-wrap {padding: 15px 0}

        .product .compare-wrap,
        .product .price-and-discount-wrap,
        .product .add-to-wrap {
            display: block;
            text-align: center;
        }
    }
</style>
<?= PopularWidget::widget() ?>

<?= ServiceBuyWidget::widget(['id' => $model->id]) ?>

frontend/views/site/error.php
<?php
/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;
use frontend\widgets\catalog\CatalogWidget;
use frontend\widgets\header\HeaderWidget;

$this->title = 'Страница не найдена';
?>
<div class="main-section variant404">
    <div class="container">
        <div class="wrap flex-wrapper">

            <?= CatalogWidget::widget() ?>

            <div class="right-part flex-wrapper flex-space-b padding-lr-15 flex-dir-col">
                <?= HeaderWidget::widget() ?>
            </div>
        </div>
        
        <div class="wrap padding-lr-15">
            <div class="content404 flex-wrapper flex-space-b">
                <div class="left-part">
                    <div class="group404">
                        <h2>4<span>0</span>4</h2>
                        <h3>Страница не найдена</h3>
                        <p>Неправильно набран адрес или такой страницы на&nbsp;сайте не&nbsp;существует.</p>
                        <a href="/" class="blue-button">Вернуться на главную</a>
                    </div>
                </div>
                <div class="right-part">
                    <img src="/img/img-3.png" alt="">
                </div>
            </div>
        </div>
    </div>
</div>

frontend/views/site/group-items.php
<?php

/**
 * @var $this     \yii\web\View
 * @var $services \common\models\Service[]
 */
use yii\helpers\Html;
use frontend\components\RenderHelper;

$isSearchPage = Yii::$app->controller->action->id == 'search';
?>
<style type="text/css">
.tabs-group.variant2 .tab {height: 455px;}
.new-bottom-part {
    display: flex !important;
    justify-content: space-between;
    padding: 5px;
    overflow: hidden;
    height: 45px;
}
.product-name-group .product-price-wrap{
    display: flex !important;
    justify-content: space-between;
    margin: 15px 0 0px;
}
.product-name-group .product-price-wrap .old-price {
    color: #909090;
    font-size: 17px;
    text-decoration: line-through;
    text-indent: 5px;
    margin-bottom: 10px;
    font-family: 'PT Sans', serif;
    font-weight: bold;
}
.product-name-group .product-price-wrap .item-price {
    font-size: 20px;
    color: #528cbc;
}

.new-bottom-part .add-to-wrap .compare-link,
.new-bottom-part .add-to-wrap .favorite-link{
    display: inline-block;
    border: 2px solid #518bbd;
    color: #518bbd;
    border-radius: 4px;
    padding: 3px;
    font-size: 20px;
    margin: 0 3px;
}
span.product-name-group {
    width: 100%;
}
.new-bottom-part .buy-button {
    font-size: 14px;
    width: auto;
    padding: 7px 14px;
    height: auto;
}
.new-bottom-part .buy-button span {
    display: inline-block;
    margin-right: 3px;
}
</style>
<?php foreach ($services as $service): ?>
    <div class="tab">
        <span class="tab-ins flex-space-b flex-dir-col flex-align-center">
            <?=Html::a(Html::img($service->getLogo()), $service->getUrl(), ['target'=>'_blank']) ?>
            <span class="product-name-group">
                <span class="cat-name"><?= Html::encode($service->serviceType->name) ?></span>
                <span class="product-name"><?= Html::a(Html::encode(RenderHelper::serviceName($service->name)), $service->getUrl(), ['target'=>'_blank']) ?></span>
                <span class="product-articul"><?= $service->code ?></span>
                <span class="product-price-wrap">
                    <?php if (Yii::$app->user->id && Yii::$app->user->identity->discountToUser): ?>
                        <span class="old-price"><?= number_format($service->price, 2, '.', ' ') ?> &#8381;</span>
                        <span class="item-price">
                            <?= number_format(
                                $service->price * (1-Yii::$app->user->identity->discountToUser->discount->discount),
                                2, '.', ' '
                            ) ?> &#8381;
                        </span>
                    <?php else: ?>
                        <span class="item-price"><?= number_format($service->price, 2, '.', ' ') ?> &#8381;</span>
                    <?php endif ?>
                </span>
            </span>
        </span>
        <span class="new-bottom-part flex-align-center">
            <div class="add-to-wrap">
            <?php echo Html::tag( 'span', '<span class="glyphicon glyphicon-heart-empty"></span>', ['item-id'=>$service->id,'class'=>'favorite-link']) ?>
            <?php echo Html::tag( 'span', '<span class="glyphicon glyphicon-stats"></span>', ['item-id'=>$service->id,'class'=>'compare-link']) ?>
            </div>
            <?php echo Html::button('<span class="glyphicon glyphicon-shopping-cart"></span>&nbsp;В корзину', ['item-id'=>$service->id,'class'=>'blue-button buy-button']) ?>
        </span>
    </div>
<?php endforeach ?>

frontend/views/site/index.php
<?php

/**
 * @var $this      \yii\web\View
 * @var $populars  \common\models\Service[]
 * @var $pages     integer
 * @var $settings  []
 * @var $advantage string
 */
use yii\helpers\Url;
use yii\helpers\Html;
use frontend\widgets\catalog\CatalogWidget;
use frontend\widgets\service\PopularWidget;
use frontend\widgets\service\NewWidget;
use frontend\widgets\news\NewsWidget;
use frontend\widgets\header\HeaderWidget;
use common\models\Settings;

$this->title = Settings::getSetting('index_title');
$this->registerMetaTag([
    'name' => 'description',
    'content' => Settings::getSetting('index_description'),
]);
$this->registerMetaTag([
    'name' => 'keywords',
    'content' => Settings::getSetting('index_keywords'),
]);
?>

<div class="main-section">
    <div class="container">
        <div class="wrap flex-wrapper">

            <?= CatalogWidget::widget(['show' => true]) ?>

            <div class="right-part flex-wrapper flex-space-b padding-lr-15 flex-dir-col">
                <?= HeaderWidget::widget() ?>
                <div class="wrapper flex-wrapper flex-space-b flex-grow-1 flex-dir-col">
                    <div class="slider-wrap">
                        <div class="slider" id="slider">
                            <?php if (!empty($banner)): ?>
                                <div class="slider-item">
                                    <img src="/uploads/<?= $banner ?>" alt="">
                                </div>
                            <?php endif; ?>
                        </div>
                    </div>
                    <div class="tab-links flex-wrapper flex-space-b flex-flow-wrap" id="tab-links">
                        <?php foreach ($quickSearch as $search): ?>
                            <a href="<?= Url::to(['site/search', 'url' => $search->url]) ?>" class="tab-link">
                                <img src="<?= $search->getLogo() ?>" alt="">
                                <span class="tab-title"><?= Html::encode($search->name) ?></span>
                            </a>
                        <?php endforeach; ?>
                    </div>
                    <div class="tab-links-flag"></div>
                </div>
            </div>
        </div>	
    </div>
</div>


<?= PopularWidget::widget() ?>

<?= NewWidget::widget() ?>

<?= NewsWidget::widget(); ?>


<section class="section">
    <div class="container">
        <h3 class="padding-lr-15">О компании</h3>
        <div class="text padding-lr-15">
            <?= $about ?>
        </div>
    </div>
</section>

frontend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Request password reset';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out your email. A link to reset password will be sent there.</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>

                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>

                <div class="form-group">
                    <?= Html::submitButton('Send', ['class' => 'btn btn-primary']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>

frontend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\SignupForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Signup';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-signup">
    <h1><?= Html::encode($this->title) ?></h1>

    <p>Please fill out the following fields to signup:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'form-signup']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'email') ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <div class="form-group">
                    <?= Html::submitButton('Signup', ['class' => 'btn btn-primary', 'name' => 'signup-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
</div>